### ISSUE TITLE
Boxxy-com minimal implementation

### ISSUE THREAD

**Issue by abeforgit** [12urenloop/Telraam#10]
This component will handle communication with the boxxy proxy.

**Comment by ajuvercr** [comment]
What is the boxxy proxy?

**Comment by abeforgit** [comment]
Basically something that pushes the live scores to the website, see [the repo](https://github.com/12urenloop/cvc/tree/master/boxxy)

**Comment by Robbe7730** [comment]
This is now handled by [Loxsi](https://github.com/12urenloop/Loxsi), which just uses Telraams API
