### ISSUE TITLE
feat: Positioners

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/Telraam#109]
A positioner is an algorithm which will calculate the data needed to represent each team on the position visualization which will be created by @Topvennie.
We would need a manager like we have for lapper so we can get data from it via the API but also select an active one which will send its data over the websocket opened by loxsi

**Comment by Topvennie** [comment]
The manager is moved to #111

**Comment by Topvennie** [comment]
Implementation of a simple / dumb lapper [7c990cc](https://github.com/12urenloop/Telraam/commit/7c990cc8b041ad177a84814902e852160a841655)
