### ISSUE TITLE
feat: WS endpoint for loxsi

### ISSUE THREAD

**Issue by NuttyShrimp** [12urenloop/Telraam#111]
Add an endpoint where loxsi can open a websocket to. We should be able to send data to out from other classes (singleton pattern?)

**Comment by jnms-me** [comment]
Assign me

**Comment by jnms-me** [comment]
See branch https://github.com/12urenloop/Telraam/tree/ws-endpoint

**Comment by jnms-me** [comment]
Websocket requests on /ws spawn a WebsocketHandler instance
Try out with https://github.com/vi/websocat (in arch, nix repos)
