### ISSUE TITLE
Determine detection message protocol

### ISSUE THREAD

**Issue by abeforgit** [12urenloop/Telraam#36]
We should decide on what kind of message the beacons should send to the telraam instance when they detect a baton.

**Comment by abeforgit** [comment]
# Proposal:

```
<<<<baton_id:short beacon_id:short timestamp:long>>>>
````
Gewoon allemaal aan elkaar, de vishaken zijn literals
example:

```
<<<<0x0001 0x0001 0xABCDABCDABCDABCD>>>>
```

**Comment by abeforgit** [comment]
Comment hierop: voorlopig houden we zeker het oude protocol omdat we CVC als backup willen behouden. Ook is het enigzins wat moeilijk om het macadress van een baton te mappen op een baton_id in de beacons, dat houden we wss beter in telraam.

**Comment by Robbe7730** [comment]
In the current beacon code, the proposal is implemented, we also no longer want to keep CVC as backup, so I think we can close this.
