### ISSUE TITLE
Simple api client

### ISSUE THREAD

**Issue by abeforgit** [12urenloop/Telraam#38]
A simple webview querying the api. 
It should at least display as much information as the old CVC webview, but more is better.

Focus on features, not styling.

**Comment by Robbe7730** [comment]
We'll make this a CLI script for now, a web-interface can always be implemented later

**Comment by ajuvercr** [comment]
This looks amazing! Is creating a cli still needed?

**Comment by FKD13** [comment]
We have a UI!
