### ISSUE TITLE
Investigate poll-based architecture

### ISSUE THREAD

**Issue by abeforgit** [12urenloop/Telraam#43]
A suggestion was raised by @redfast00 to consider a poll-based architecture. This would mean that beacons do not send messages to Telraam, but store their detections and provide a simple endpoint where Telraam can query for all the messages from a certain timestamp. 

It is as of yet unclear what advantages and disadvantages this would bring, so discuss below.

One thing to mention is that it should not be too difficult to implement both with the current architecture.

**Comment by redfast00** [comment]
Advantages: if telraam loses state or the network disconnects, no work needs to be done to fix the Telraam state

**Comment by abeforgit** [comment]
> Advantages: if telraam loses state or the network disconnects, no work needs to be done to fix the Telraam state

this implies that beacons keep all messages in memory since the start of the event

not saying thats a problem, just to clarify

**Comment by abeforgit** [comment]
one disadvantage is that the beacons become more complex

But then again my intuition is that that complexity will be offset by simpler code on the telraam side

for the record I quite like the idea and I think we should definitely give it a try

**Comment by redfast00** [comment]
The beacons become an append-only database and a web server, should be pretty doable with like 50 lines of Python. I think the biggest issue on the detection station will be interfacing with the BTLE hardware.

**Comment by abeforgit** [comment]
> The beacons become an append-only database and a web server, should be pretty doable with like 50 lines of Python. I think the biggest issue on the detection station will be interfacing with the BTLE hardware.

iirc thats just through bluetoothctl, so I dont think that'll be too much of a problem either

**Comment by Robbe7730** [comment]
In a recent discussion, we have decided to switch to a full poll-based architecture. The stations will keep track of all detections, and can be polled with "this is my last detection, give me all detections after that".

Telraam currently works with a push-based architecture, so we have to change this. However, we will temporarily use a script to connect Telraam and the stations

**Comment by redfast00** [comment]
This was implemented
